# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Server
source:           .
destination:      _gh_pages
host:             0.0.0.0
port:             10006
url:              http://holdirbootstrap.de
encoding:         UTF-8

exclude:
  - jade
  - src
  - vendor

# Custom vars
current_version:  3.3.2
repo:             https://github.com/twbs/bootstrap
sass_repo:        https://github.com/twbs/bootstrap-sass

download:
  source:         https://github.com/twbs/bootstrap/archive/v3.3.2.zip
  dist:           https://github.com/twbs/bootstrap/releases/download/v3.3.2/bootstrap-3.3.2-dist.zip
  sass:           https://github.com/twbs/bootstrap-sass/archive/v3.3.3.tar.gz

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn:
  css:            https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css
  css_theme:      https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css
  js:             https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js
